CREATE DATABASE IF NOT EXISTS `[DATABASE_NAME]`;

CREATE USER IF NOT EXISTS '[DATABASE_USERNAME]'@localhost IDENTIFIED BY '[DATABASE_PASSWORD]';

GRANT ALL PRIVILEGES ON `[DATABASE_NAME]`.* TO '[DATABASE_USERNAME]'@localhost;
FLUSH PRIVILEGES;