CREATE DATABASE IF NOT EXISTS `poly_trading_bot`;

CREATE USER IF NOT EXISTS 'POLY_ADMIN'@localhost IDENTIFIED BY 'POLY123@';

GRANT ALL PRIVILEGES ON `poly_trading_bot`.* TO 'POLY_ADMIN'@localhost;

FLUSH PRIVILEGES;